### ISSUE TITLE
Obsolete/broken code to save and restore state on SIGHUP

### ISSUE THREAD

**Issue by bzeller** [nemomobile/mapplauncherd#33]
There seems to be obsolete code that should rexec the launcher daemon on a SIGHUP (daemon.cpp `void Daemon::reExec()` ).

The state then is saved, but to re-exec the following arguments are used:  

    char* argv[] = { const_cast<char*>("/usr/bin/applauncherd.bin"),
                     const_cast<char*>("--re-exec"),
                     const_cast<char*>("                                                  "),
                     NULL};

Since there is no applauncherd.bin this code is probably obsolete or broken.
Should that code be removed or fixed?

**Comment by faenil** [comment]
maybe @thp ?
